project_id = "xkwttqsoyjiejtysixuk"

[functions.process-payment]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false